workflows:
  flutter:
    name: Flutter workflow
    instance_type: mac_mini
    scripts:
      - name: Install Flutter
        script: |
          flutter doctor
          flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
